In [ ]:
!pip install keras

In [ ]:
from keras.preprocessing.text import text_to_word_sequence, Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
texts = [
    "Keras is an open-source software library that provides a Python interface for artificial neural networks.",
    "Keras acts as an interface for the TensorFlow library.",
    "It was developed by François Chollet, a Google engineer.",
    "Keras allows for easy and fast prototyping, supports both convolutional networks and recurrent networks, and runs seamlessly on CPU and GPU."
]

In [ ]:
word_sequences = [text_to_word_sequence(text) for text in texts]

for i, sequence in enumerate(word_sequences):
    print(f"Text {i+1}: {sequence}")

Text 1: ['keras', 'is', 'an', 'open', 'source', 'software', 'library', 'that', 'provides', 'a', 'python', 'interface', 'for', 'artificial', 'neural', 'networks']
Text 2: ['keras', 'acts', 'as', 'an', 'interface', 'for', 'the', 'tensorflow', 'library']
Text 3: ['it', 'was', 'developed', 'by', 'françois', 'chollet', 'a', 'google', 'engineer']
Text 4: ['keras', 'allows', 'for', 'easy', 'and', 'fast', 'prototyping', 'supports', 'both', 'convolutional', 'networks', 'and', 'recurrent', 'networks', 'and', 'runs', 'seamlessly', 'on', 'cpu', 'and', 'gpu']


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

for i, sequence in enumerate(sequences):
    print(f"Text {i+1} sequence: {sequence}")

Text 1 sequence: [2, 9, 5, 10, 11, 12, 6, 13, 14, 7, 15, 8, 3, 16, 17, 4]
Text 2 sequence: [2, 18, 19, 5, 8, 3, 20, 21, 6]
Text 3 sequence: [22, 23, 24, 25, 26, 27, 7, 28, 29]
Text 4 sequence: [2, 30, 3, 31, 1, 32, 33, 34, 35, 36, 4, 1, 37, 4, 1, 38, 39, 40, 41, 1, 42]


In [ ]:
max_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_length)

print("Padded sequences:")
print(padded_sequences)

Padded sequences:
[[ 0  0  0  0  0  2  9  5 10 11 12  6 13 14  7 15  8  3 16 17  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2 18 19  5  8  3 20 21  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 22 23 24 25 26 27  7 28 29]
 [ 2 30  3 31  1 32 33 34 35 36  4  1 37  4  1 38 39 40 41  1 42]]


In [ ]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=50, input_length=max_length))
model.add(LSTM(units=50))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 21, 50)            2150      
                                                                 
 lstm (LSTM)                 (None, 50)                20200     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 22401 (87.50 KB)
Trainable params: 22401 (87.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
labels = np.array([1, 0, 1, 0])

X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=2, validation_data=(X_test, y_test))

Epoch 1/10
2/2 [==============================] - 4s 1s/step - loss: 0.6923 - accuracy: 0.3333 - val_loss: 0.7017 - val_accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 135ms/step - loss: 0.6805 - accuracy: 1.0000 - val_loss: 0.7070 - val_accuracy: 0.0000e+00
Epoch 3/10
2/2 [==============================] - 0s 167ms/step - loss: 0.6709 - accuracy: 1.0000 - val_loss: 0.7161 - val_accuracy: 0.0000e+00
Epoch 4/10
2/2 [==============================] - 0s 142ms/step - loss: 0.6598 - accuracy: 1.0000 - val_loss: 0.7287 - val_accuracy: 0.0000e+00
Epoch 5/10
2/2 [==============================] - 0s 128ms/step - loss: 0.6468 - accuracy: 1.0000 - val_loss: 0.7458 - val_accuracy: 0.0000e+00
Epoch 6/10
2/2 [==============================] - 0s 96ms/step - loss: 0.6299 - accuracy: 1.0000 - val_loss: 0.7698 - val_accuracy: 0.0000e+00
Epoch 7/10
2/2 [==============================] - 0s 92ms/step - loss: 0.6097 - accuracy: 1.0000 - val_loss: 0.8041 - val_accuracy: 0.0000e+

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")

1/1 [==============================] - 0s 45ms/step - loss: 1.0754 - accuracy: 0.0000e+00
Test Loss: 1.0753716230392456
Test Accuracy: 0.0
